### ISSUE TITLE
Ability to program the arduino from the pi

### ISSUE THREAD

**Issue by ashirley** [braidstag/arduino-milestag#16]
This might need new electronics to enable the pi to reset the arduino (while still keeping the pi power on) in order to program it

**Comment by neothermic** [comment]
Flashing firmware is relatively simple and works reliably. Building it on the Pi is more challenging, it may be far easier and more coherent to build it and bundle it in the repo. 

Hardware considerations are being dealt with and shouldn't be a problem with new board design.

**Comment by neothermic** [comment]
From a software point of view this is done, hardware works, as long as circuitry is successful this can be considered closed.
